name: Teleport Auth
author: Gravitational, Inc.
description: Authenticates your workflow so it can use Teleport's `tctl` and `tsh` with the magic of Machine ID.
inputs:
    anonymous-telemetry:
        description: Enables anonymous telemetry. See https://goteleport.com/docs/machine-id/reference/telemetry/ for more information.
        required: false
    certificate-ttl:
        description: Specify the length that the generated credentials should be valid for. Defaults to "1h"
        required: false
    proxy:
        description: Specify the address of your Teleport Proxy.
        required: true
    token:
        description: Specify the Teleport token to use to join.
        required: true
runs:
    using: node16
    main: dist/index.js
branding:
    color: purple
    icon: terminal
